version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - '8000:8000'